[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aido-wl-ref"
version = "0.1.1"
description = "Minimum public reference and reproducibility package for AIDO-WL"
requires-python = ">=3.10"
authors = [
  {name = "Sin Guan Kong"}
]
readme = "README.md"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent"
]

[project.scripts]
aido-wl-ref = "aido_wl_ref.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
